spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db?useSSL=false
    username: root
    password: Me@29012019

#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER


  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  #  jpa:
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  #JPA Settings
  jpa.hibernate.ddl_auto: update